<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
/**
 * @OA\Info(
 *      version="1.0.0",
 *      title="体育接口文档",
 *      description="行云流水，指尖留香",
 * )
 */

/**
 * @OA\Schema(
 *   schema="足球比赛列表",
 *   @OA\Property(
 *      property="matchId",
 *      type="integer",
 *      description="比赛id",
 *   ),
 *   @OA\Property(
 *      property="leagueId",
 *      type="integer",
 *      description="联赛/杯赛ID",
 *   ),
 *   @OA\Property(
 *      property="league",
 *      type="object",
 *      description="联赛",
 *      @OA\Property(
 *          property="leagueNameCn",
 *          type="string",
 *          description="中文全称",
 *      ),
 *      @OA\Property(
 *          property="leagueNameCnShort",
 *          type="string",
 *          description="中文简称",
 *      ),
 *   ),
 *   @OA\Property(
 *      property="matchStartTime",
 *      type="integer",
 *      description="比赛开始时间(时间戳)",
 *   ),
 *   @OA\Property(
 *      property="state",
 *      type="integer",
 *      description="比赛状态：10：上半场，20：中场，30：下半场，40：加时，50：点球，60：未开赛，70：待定，80：延迟，90：中断，100：腰斩，110：取消，120：完场    比赛状态（海鸥）:-14:推迟，-13:中断，-12:腰斩，-11:待定，-10:取消，-1.完场，0:未开始，1:上半场，2:中场，3:下半场，4:加时，5:点球",
 *   ),
 *   @OA\Property(
 *      property="state_str",
 *      type="string",
 *      description="比赛状态文本",
 *   ),
 *   @OA\Property(
 *      property="is_playing",
 *      type="bool",
 *      description="1未开赛，2比赛中，3已完赛",
 *   ),
 *   @OA\Property(
 *      property="live_url",
 *      type="object",
 *      description="如果比赛在进行中并且此地址不为空，使用此直播地址",
 *      @OA\Property(
 *          type="string",
 *          description="地址",
 *      ),
 *   ),
 *   @OA\Property(
 *      property="isNeutral",
 *      type="integer",
 *      description="是否中立场，1：是，2：否",
 *   ),
 *   @OA\Property(
 *      property="locationCn",
 *      type="string",
 *      description="比赛场地(中文,繁体也使用这个字段)",
 *   ),
 *   @OA\Property(
 *      property="locationEn",
 *      type="string",
 *      description="比赛场地(英文)",
 *   ),
 *   @OA\Property(
 *      property="homeId",
 *      type="integer",
 *      description="主队ID",
 *   ),
 *   @OA\Property(
 *      property="homeTeam",
 *      type="object",
 *      description="主队",
 *      @OA\Property(
 *          property="nameCn",
 *          type="string",
 *          description="中文简体",
 *      ),
 *      @OA\Property(
 *          property="nameTrad",
 *          type="string",
 *          description="中文繁体",
 *      ),
 *      @OA\Property(
 *          property="nameEn",
 *          type="string",
 *          description="英文",
 *      ),
 *      @OA\Property(
 *          property="logo",
 *          type="string",
 *          description="队伍logo",
 *      ),
 *   ),
 *   @OA\Property(
 *      property="awayId",
 *      type="integer",
 *      description="客队ID",
 *   ),
 *   @OA\Property(
 *      property="awayTeam",
 *      type="object",
 *      description="客队",
 *      @OA\Property(
 *          property="nameCn",
 *          type="string",
 *          description="中文简体",
 *      ),
 *      @OA\Property(
 *          property="nameTrad",
 *          type="string",
 *          description="中文繁体",
 *      ),
 *      @OA\Property(
 *          property="nameEn",
 *          type="string",
 *          description="英文",
 *      ),
 *      @OA\Property(
 *          property="logo",
 *          type="string",
 *          description="队伍logo",
 *      ),
 *   ),
 *   @OA\Property(
 *      property="homeScore",
 *      type="integer",
 *      description="主队全场比分",
 *   ),
 *   @OA\Property(
 *      property="awayScore",
 *      type="integer",
 *      description="客队全场比分",
 *   ),
 *   @OA\Property(
 *      property="homeHalfScore",
 *      type="integer",
 *      description="主队半场比分",
 *   ),
 *   @OA\Property(
 *      property="awayHalfScore",
 *      type="integer",
 *      description="客队半场比分",
 *   ),
 *   @OA\Property(
 *      property="homeCornerNum",
 *      type="integer",
 *      description="主队角球数",
 *   ),
 *   @OA\Property(
 *      property="awayCornerNum",
 *      type="integer",
 *      description="客队角球数",
 *   ),
 *   @OA\Property(
 *      property="extraFirstKick",
 *      type="integer",
 *      description="加时: 先开球方，1：主队先开球，2：客队先开球",
 *   ),
 *   @OA\Property(
 *      property="extraNormalTime",
 *      type="integer",
 *      description="加时: 常规时间",
 *   ),
 *   @OA\Property(
 *      property="extraNormalScore",
 *      type="string",
 *      description="加时: 常规时间的比分",
 *   ),
 *   @OA\Property(
 *      property="extraTwoLegsScore",
 *      type="string",
 *      description="加时: 两回合总比分，该字段仅在比赛有加时、点球的情况才更新",
 *   ),
 *   @OA\Property(
 *      property="extraType",
 *      type="integer",
 *      description="加时: 加时阶段类型，1:120分钟，2：加时，3：加时中",
 *   ),
 *   @OA\Property(
 *      property="extraScore",
 *      type="string",
 *      description="加时: 加时阶段比分",
 *   ),
 *   @OA\Property(
 *      property="extraPenaltyKickScore",
 *      type="string",
 *      description="加时: 点球大战比分",
 *   ),
 *   @OA\Property(
 *      property="extraWin",
 *      type="integer",
 *      description="加时: 获胜方，1：主队获胜，2：客队获胜",
 *   ),
 *   @OA\Property(
 *      property="letgoalHomeOdds",
 *      type="integer",
 *      description="让球即时主队赔率",
 *   ),
 *   @OA\Property(
 *      property="letgoalGoal",
 *      type="integer",
 *      description="让球即时盘口",
 *   ),
 *   @OA\Property(
 *      property="letgoalAwayOdds",
 *      type="integer",
 *      description="让球即时客队赔率",
 *   ),
 *   @OA\Property(
 *      property="letgoalIsEntertained",
 *      type="integer",
 *      description="亚盘：是否封盘,1：默认，2：临时性封盘或停止走地",
 *   ),
 *   @OA\Property(
 *      property="europeHomeOdds",
 *      type="integer",
 *      description="欧赔即时主队赔率",
 *   ),
 *   @OA\Property(
 *      property="europeFlatOdds",
 *      type="integer",
 *      description="欧赔即时盘口",
 *   ),
 *   @OA\Property(
 *      property="europeAwayOdds",
 *      type="integer",
 *      description="欧赔即时客队赔率",
 *   ),
 *   @OA\Property(
 *      property="europeIsEntertained",
 *      type="integer",
 *      description="欧赔：是否封盘,1：默认，2：临时性封盘或停止走地",
 *   ),
 *   @OA\Property(
 *      property="totalScoreHomeOdds",
 *      type="integer",
 *      description="大小球即时主队赔率",
 *   ),
 *   @OA\Property(
 *      property="totalScoreGoal",
 *      type="integer",
 *      description="大小球即时盘口",
 *   ),
 *   @OA\Property(
 *      property="totalScoreAwayOdds",
 *      type="integer",
 *      description="大小球即时客队赔率",
 *   ),
 *   @OA\Property(
 *      property="totalScoreIsEntertained",
 *      type="integer",
 *      description="大小球：是否封盘, 1：默认，2：临时性封盘或停止走地",
 *   ),
 *   @OA\Property(
 *      property="hasSources",
 *      type="integer",
 *      description="是否有情报,0：无，1：有",
 *   ),
 *   @OA\Property(
 *      property="hasLive",
 *      type="integer",
 *      description="是否有直播（购买直播信号可关联），无使用时，该字段无意义,0：无，1：有",
 *   ),
 *   @OA\Property(
 *      property="weatherEn",
 *      type="string",
 *      description="天气（英文）",
 *   ),
 *   @OA\Property(
 *      property="weatherCn",
 *      type="string",
 *      description="天气（中文）",
 *   ),
 *   @OA\Property(
 *      property="weatherIcon",
 *      type="string",
 *      description="天气图标",
 *   ),
 *   @OA\Property(
 *      property="temperature",
 *      type="string",
 *      description="温度",
 *   ),
 *   @OA\Property(
 *      property="match_date",
 *      type="string",
 *      description="比赛日期",
 *   ),
 * )
 **/


/**
 * @OA\Schema(
 *   schema="篮球比赛列表",
 *   @OA\Property(
 *      property="matchId",
 *      type="integer",
 *      description="比赛id",
 *   ),
 *   @OA\Property(
 *      property="leagueId",
 *      type="integer",
 *      description="联赛/杯赛ID",
 *   ),
 *   @OA\Property(
 *      property="league",
 *      type="object",
 *      description="联赛",
 *      @OA\Property(
 *          property="leagueNameCn",
 *          type="string",
 *          description="中文全称",
 *      ),
 *      @OA\Property(
 *          property="leagueNameCnShort",
 *          type="string",
 *          description="中文简称",
 *      ),
 *   ),
 *   @OA\Property(
 *      property="matchStartTime",
 *      type="integer",
 *      description="比赛开始时间(时间戳)",
 *   ),
 *   @OA\Property(
 *      property="state",
 *      type="integer",
 *      description="比赛状态：10：第一节，20：第一节完，30：第二节，40：第二节完，50：第三节，60：第三节完，70：第四节，80：加时，90：未开赛，100：待定，110：延迟，120：中断，130：腰斩，140：取消，150：完场     比赛状态（海鸥）:  0：比赛一场，1：未开赛，2：第一节，3：第一节完，4：第二节，5：第二节完，6：第三节，7：第三节完，8：第四节，9：加时，10：完场，11：中断，12：取消，13：延期，14：腰斩，15：待定",
 *   ),
 *   @OA\Property(
 *      property="state_str",
 *      type="string",
 *      description="比赛状态文本",
 *   ),
 *   @OA\Property(
 *      property="is_playing",
 *      type="integer",
 *      description="1未开赛，2比赛中，3已完赛",
 *   ),
 *   @OA\Property(
 *      property="live_url",
 *      type="object",
 *      description="如果比赛在进行中并且此地址不为空，使用此直播地址",
 *     @OA\Property(
 *          type="string",
 *          description="地址",
 *      ),
 *   ),
 *   @OA\Property(
 *      property="homeId",
 *      type="integer",
 *      description="主队ID",
 *   ),
 *   @OA\Property(
 *      property="homeTeam",
 *      type="object",
 *      description="主队",
 *      @OA\Property(
 *          property="nameCn",
 *          type="string",
 *          description="中文全称",
 *      ),
 *      @OA\Property(
 *          property="nameCnShort",
 *          type="string",
 *          description="中文简称",
 *      ),
 *      @OA\Property(
 *          property="logo",
 *          type="string",
 *          description="队伍图标",
 *      ),
 *   ),
 *   @OA\Property(
 *      property="awayId",
 *      type="integer",
 *      description="客队ID",
 *   ),
 *   @OA\Property(
 *      property="awayTeam",
 *      type="object",
 *      description="客队",
 *      @OA\Property(
 *          property="nameCn",
 *          type="string",
 *          description="中文全称",
 *      ),
 *      @OA\Property(
 *          property="nameCnShort",
 *          type="string",
 *          description="中文简称",
 *      ),
 *      @OA\Property(
 *          property="logo",
 *          type="string",
 *          description="队伍图标",
 *      ),
 *   ),
 *   @OA\Property(
 *      property="matchConductTime",
 *      type="integer",
 *      description="当前小节所剩时间(分钟:秒)",
 *   ),
 *   @OA\Property(
 *      property="homeScore",
 *      type="integer",
 *      description="主队全场比分",
 *   ),
 *   @OA\Property(
 *      property="awayScore",
 *      type="integer",
 *      description="客队全场比分",
 *   ),
 *   @OA\Property(
 *      property="nodeCount",
 *      type="integer",
 *      description="总节数",
 *   ),
 *   @OA\Property(
 *      property="homeNode1Score",
 *      type="integer",
 *      description="主队第一节比分",
 *   ),
 *   @OA\Property(
 *      property="homeNode2Score",
 *      type="integer",
 *      description="主队第二节比分",
 *   ),
 *   @OA\Property(
 *      property="homeNode3Score",
 *      type="integer",
 *      description="主队第三节比分",
 *   ),
 *   @OA\Property(
 *      property="homeNode4Score",
 *      type="integer",
 *      description="主队第四节比分",
 *   ),
 *   @OA\Property(
 *      property="homeNode5Score",
 *      type="integer",
 *      description="主队加时比分",
 *   ),
 *   @OA\Property(
 *      property="awayNode1Score",
 *      type="integer",
 *      description="客队第一节比分",
 *   ),
 *   @OA\Property(
 *      property="awayNode2Score",
 *      type="integer",
 *      description="客队第二节比分",
 *   ),
 *   @OA\Property(
 *      property="awayNode3Score",
 *      type="integer",
 *      description="客队第三节比分",
 *   ),
 *   @OA\Property(
 *      property="awayNode4Score",
 *      type="integer",
 *      description="客队第四节比分",
 *   ),
 *   @OA\Property(
 *      property="awayNode5Score",
 *      type="integer",
 *      description="客队加时比分",
 *   ),
 *   @OA\Property(
 *      property="letgoalHomeOdds",
 *      type="string",
 *      description="让球即时主队赔率",
 *   ),
 *   @OA\Property(
 *      property="letgoalGoal",
 *      type="integer",
 *      description="让球即时盘口",
 *   ),
 *   @OA\Property(
 *      property="letgoalAwayOdds",
 *      type="string",
 *      description="让球即时客队赔率",
 *   ),
 *   @OA\Property(
 *      property="letgoalIsEntertained",
 *      type="string",
 *      description="亚盘：是否封盘，0：表示没有盘口 ，1：未封盘  ，2：临时性封盘或停止走地",
 *   ),
 *   @OA\Property(
 *      property="europeHomeOdds",
 *      type="integer",
 *      description="欧赔即时主队赔率",
 *   ),
 *   @OA\Property(
 *      property="europeFlatOdds",
 *      type="integer",
 *      description="欧赔即时盘口",
 *   ),
 *   @OA\Property(
 *      property="europeAwayOdds",
 *      type="integer",
 *      description="欧赔即时客队赔率",
 *   ),
 *   @OA\Property(
 *      property="europeIsEntertained",
 *      type="integer",
 *      description="欧赔：是否封盘，0：表示没有盘口，1：未封盘，2：临时性封盘或停止走地",
 *   ),
 *   @OA\Property(
 *      property="totalScoreHomeOdds",
 *      type="integer",
 *      description="大小球即时主队赔率",
 *   ),
 *   @OA\Property(
 *      property="totalScoreGoal",
 *      type="integer",
 *      description="大小球即时盘口",
 *   ),
 *   @OA\Property(
 *      property="totalScoreAwayOdds",
 *      type="integer",
 *      description="大小球即时客队赔率",
 *   ),
 *   @OA\Property(
 *      property="totalScoreIsEntertained",
 *      type="integer",
 *      description="大小球：是否封盘，0：表示没有盘口，1：未封盘，2：临时性封盘或停止走地",
 *   ),
 *   @OA\Property(
 *      property="isSources",
 *      type="integer",
 *      description="是否有情报,0：无，1：有",
 *   ),
 *   @OA\Property(
 *      property="isAnimation",
 *      type="integer",
 *      description="是否有动画 （该字段无意思，不提供动画数据）,0：无，1：有",
 *   ),
 *   @OA\Property(
 *      property="isLive",
 *      type="integer",
 *      description="是否有直播（购买直播信号可关联），无使用时，该字段无意义,0：无，1：有",
 *   ),
 *   @OA\Property(
 *      property="homeNodePauseCount",
 *      type="integer",
 *      description="主队剩暂停数",
 *   ),
 *   @OA\Property(
 *      property="awayNodePauseCount",
 *      type="integer",
 *      description="客队剩暂停数",
 *   ),
 *   @OA\Property(
 *      property="homeNodeFoulsCount",
 *      type="integer",
 *      description="主队犯规数",
 *   ),
 *   @OA\Property(
 *      property="awayNodeFoulsCount",
 *      type="integer",
 *      description="客队犯规数",
 *   ),
 *   @OA\Property(
 *      property="homeAssists",
 *      type="string",
 *      description="主队助攻数",
 *   ),
 *   @OA\Property(
 *      property="homeSteals",
 *      type="string",
 *      description="主队抢断数",
 *   ),
 *   @OA\Property(
 *      property="homeBlocks",
 *      type="string",
 *      description="主队盖帽数",
 *   ),
 *   @OA\Property(
 *      property="awayAssists",
 *      type="string",
 *      description="客队助攻数",
 *   ),
 *   @OA\Property(
 *      property="awaySteals",
 *      type="string",
 *      description="客队抢断数",
 *   ),
 *   @OA\Property(
 *      property="awayBlocks",
 *      type="string",
 *      description="客队盖帽数",
 *   ),
 *   @OA\Property(
 *      property="homeThreeCount",
 *      type="string",
 *      description="主队3分球数",
 *   ),
 *   @OA\Property(
 *      property="homeTwoCount",
 *      type="string",
 *      description="主队2分球数",
 *   ),
 *   @OA\Property(
 *      property="homeFreeCount",
 *      type="string",
 *      description="主队罚球数",
 *   ),
 *   @OA\Property(
 *      property="homeFreeRate",
 *      type="string",
 *      description="主队罚球命中率",
 *   ),
 *   @OA\Property(
 *      property="awayThreeCount",
 *      type="string",
 *      description="客队3分球数",
 *   ),
 *   @OA\Property(
 *      property="awayTwoCount",
 *      type="string",
 *      description="客队2分球数",
 *   ),
 *   @OA\Property(
 *      property="awayFreeCount",
 *      type="string",
 *      description="客队罚球数",
 *   ),
 *   @OA\Property(
 *      property="awayFreeRate",
 *      type="string",
 *      description="客队罚球命中率",
 *   ),
 *   @OA\Property(
 *      property="match_date",
 *      type="string",
 *      description="比赛日期",
 *   ),
 * )
 **/

/**
 * @OA\Schema(
 *   schema="直播间列表",
 *   @OA\Property(
 *      property="uid",
 *      type="integer",
 *      description="用户",
 *   ),
 *   @OA\Property(
 *      property="user",
 *      type="object",
 *      description="用户信息",
 *      @OA\Property(
 *          property="user_nicename",
 *          type="string",
 *          description="用户昵称",
 *      ),
 *      @OA\Property(
 *          property="avatar",
 *          type="string",
 *          description="用户头像",
 *      ),
 *      @OA\Property(
 *          property="avatar_thumb",
 *          type="string",
 *          description="用户小头像",
 *      ),
 *      @OA\Property(
 *          property="viewnum",
 *          type="string",
 *          description="主播热度",
 *      ),
 *   ),
 *   @OA\Property(
 *      property="showid",
 *      type="integer",
 *      description="直播标识",
 *   ),
 *   @OA\Property(
 *      property="islive",
 *      type="integer",
 *      description="直播状态",
 *   ),
 *   @OA\Property(
 *      property="starttime",
 *      type="integer",
 *      description="开播时间",
 *   ),
 *   @OA\Property(
 *      property="title",
 *      type="integer",
 *      description="标题",
 *   ),
 *   @OA\Property(
 *      property="province",
 *      type="integer",
 *      description="省份",
 *   ),
 *   @OA\Property(
 *      property="city",
 *      type="integer",
 *      description="城市",
 *   ),
 *   @OA\Property(
 *      property="stream",
 *      type="integer",
 *      description="流名",
 *   ),
 *   @OA\Property(
 *      property="thumb",
 *      type="integer",
 *      description="封面图",
 *   ),
 *   @OA\Property(
 *      property="pull",
 *      type="integer",
 *      description="播流地址",
 *   ),
 *   @OA\Property(
 *      property="lng",
 *      type="integer",
 *      description="经度",
 *   ),
 *   @OA\Property(
 *      property="lat",
 *      type="integer",
 *      description="维度",
 *   ),
 *   @OA\Property(
 *      property="type",
 *      type="integer",
 *      description="直播类型",
 *   ),
 *   @OA\Property(
 *      property="type_val",
 *      type="integer",
 *      description="类型值",
 *   ),
 *   @OA\Property(
 *      property="isvideo",
 *      type="integer",
 *      description="是否假视频",
 *   ),
 *   @OA\Property(
 *      property="wy_cid",
 *      type="integer",
 *      description="网易房间ID(当不使用网易是默认为空)",
 *   ),
 *   @OA\Property(
 *      property="goodnum",
 *      type="integer",
 *      description="靓号",
 *   ),
 *   @OA\Property(
 *      property="anyway",
 *      type="integer",
 *      description="横竖屏，0表示竖屏，1表示横屏",
 *   ),
 *   @OA\Property(
 *      property="liveclassid",
 *      type="integer",
 *      description="直播分类ID",
 *   ),
 *   @OA\Property(
 *      property="hotvotes",
 *      type="integer",
 *      description="热门礼物总额",
 *   ),
 *   @OA\Property(
 *      property="pkuid",
 *      type="integer",
 *      description="PK对方ID",
 *   ),
 *   @OA\Property(
 *      property="pkstream",
 *      type="integer",
 *      description="pk对方的流名",
 *   ),
 *   @OA\Property(
 *      property="ismic",
 *      type="integer",
 *      description="连麦开关，0是关，1是开",
 *   ),
 *   @OA\Property(
 *      property="ishot",
 *      type="integer",
 *      description="是否热门",
 *   ),
 *   @OA\Property(
 *      property="isrecommend",
 *      type="integer",
 *      description="是否推荐",
 *   ),
 *   @OA\Property(
 *      property="deviceinfo",
 *      type="integer",
 *      description="设备信息",
 *   ),
 *   @OA\Property(
 *      property="isshop",
 *      type="integer",
 *      description="是否开启店铺",
 *   ),
 *   @OA\Property(
 *      property="game_action",
 *      type="integer",
 *      description="游戏类型",
 *   ),
 *   @OA\Property(
 *      property="banker_coin",
 *      type="integer",
 *      description="庄家余额",
 *   ),
 *   @OA\Property(
 *      property="isoff",
 *      type="integer",
 *      description="是否断流，0否1是",
 *   ),
 *   @OA\Property(
 *      property="offtime",
 *      type="integer",
 *      description="断流时间",
 *   ),
 *   @OA\Property(
 *      property="recom_sort",
 *      type="integer",
 *      description="推荐排序",
 *   ),
 *   @OA\Property(
 *      property="notice",
 *      type="integer",
 *      description="直播公告",
 *   ),
 *   @OA\Property(
 *      property="match_id",
 *      type="integer",
 *      description="关联得赛事ID",
 *   ),
 *   @OA\Property(
 *      property="pic_full_url",
 *      type="integer",
 *      description="当前主播截图",
 *   ),
 * )
 **/


/**
 * @OA\Schema(
 *   schema="纳米-足球比赛列表",
 *   @OA\Property(
 *      property="id",
 *      type="integer",
 *      description="比赛id",
 *   ),
 *   @OA\Property(
 *      property="season_id",
 *      type="integer",
 *      description="赛季ID",
 *   ),
 *   @OA\Property(
 *      property="competition_id",
 *      type="integer",
 *      description="赛事/联赛id",
 *   ),
 *   @OA\Property(
 *      property="league",
 *      type="object",
 *      description="赛事/联赛",
 *      @OA\Property(
 *          property="category_id",
 *          type="string",
 *          description="分类ID",
 *      ),
 *      @OA\Property(
 *          property="country_id",
 *          type="integer",
 *          description="国家ID",
 *      ),
 *      @OA\Property(
 *          property="name_zh",
 *          type="string",
 *          description="中文名称",
 *      ),
 *      @OA\Property(
 *          property="name_zht",
 *          type="string",
 *          description="粤语名称",
 *      ),
 *      @OA\Property(
 *          property="name_en",
 *          type="string",
 *          description="英文名称",
 *      ),
 *      @OA\Property(
 *          property="short_name_zh",
 *          type="string",
 *          description="中文简称",
 *      ),
 *      @OA\Property(
 *          property="short_name_zht",
 *          type="string",
 *          description="粤语简称",
 *      ),
 *      @OA\Property(
 *          property="short_name_en",
 *          type="string",
 *          description="英文简称",
 *      ),
 *      @OA\Property(
 *          property="logo",
 *          type="string",
 *          description="logo",
 *      ),
 *      @OA\Property(
 *          property="type",
 *          type="integer",
 *          description="类型：0-未知、1-联赛、2-杯赛、3-友谊赛",
 *      ),
 *      @OA\Property(
 *          property="cur_season_id",
 *          type="integer",
 *          description="当前赛季id",
 *      ),
 *      @OA\Property(
 *          property="cur_stage_id",
 *          type="integer",
 *          description="当前阶段id",
 *      ),
 *      @OA\Property(
 *          property="cur_round",
 *          type="integer",
 *          description="当前轮次",
 *      ),
 *      @OA\Property(
 *          property="round_count",
 *          type="integer",
 *          description="总轮次",
 *      ),
 *      @OA\Property(
 *          property="title_holder",
 *          type="string",
 *          description="卫冕冠军 字段说明（有数据，字段存在）",
 *      ),
 *      @OA\Property(
 *          property="most_titles",
 *          type="string",
 *          description="夺冠最多球队 字段说明（有数据，字段存在）	",
 *      ),
 *      @OA\Property(
 *          property="newcomers",
 *          type="string",
 *          description="晋级淘汰球队 字段说明（有数据，字段存在）	",
 *      ),
 *      @OA\Property(
 *          property="divisions",
 *          type="string",
 *          description="赛事层级",
 *      ),
 *      @OA\Property(
 *          property="host",
 *          type="string",
 *          description="东道主",
 *      ),
 *      @OA\Property(
 *          property="primary_color",
 *          type="string",
 *          description="主颜色",
 *      ),
 *      @OA\Property(
 *          property="secondary_color",
 *          type="string",
 *          description="次颜色",
 *      ),
 *   ),
 *   @OA\Property(
 *      property="match_time",
 *      type="integer",
 *      description="比赛开始时间(时间戳)",
 *   ),
 *   @OA\Property(
 *      property="status_id",
 *      type="integer",
 *      description="比赛状态： |1|未开赛 |2|上半场 |3|中场 |4|下半场 |5|加时赛 |6|加时赛(弃用) |7|点球决战 |8|完场 |9|推迟 |10|中断 |11|腰斩 |12|取消 |13|待定 ",
 *   ),
 *   @OA\Property(
 *      property="home_team_id",
 *      type="integer",
 *      description="主队ID",
 *   ),
 *   @OA\Property(
 *      property="away_team_id",
 *      type="integer",
 *      description="客队ID",
 *   ),
 *   @OA\Property(
 *      property="neutral",
 *      type="integer",
 *      description="是否中立场，1-是、0-否",
 *   ),
 *   @OA\Property(
 *      property="note",
 *      type="string",
 *      description="备注",
 *   ),
 *   @OA\Property(
 *      property="home_scores",
 *      type="array",
 *      description=" 比分字段说明：[比分(常规时间),半场比分,红牌,黄牌,角球，-1表示没有角球数据,加时比分(120分钟)，加时赛才有,点球大战比分，点球大战才有]",
 *      @OA\Items(
 *                  type="integer",  example="1, 0, 0, 0, -1, 0, 0"
 *               )
 *   ),
 *   @OA\Property(
 *      property="away_scores",
 *      type="array",
 *      description="比分字段说明：[比分(常规时间),半场比分,红牌,黄牌,角球，-1表示没有角球数据,加时比分(120分钟)，加时赛才有,点球大战比分，点球大战才有]",
 *      @OA\Items(
 *                  type="integer",  example="1, 0, 0, 0, -1, 0, 0"
 *              )
 *   ),
 *   @OA\Property(
 *      property="home_position",
 *      type="integer",
 *      description="主队排名",
 *   ),
 *   @OA\Property(
 *      property="away_position",
 *      type="integer",
 *      description="客队排名",
 *   ),
 *   @OA\Property(
 *      property="coverage",
 *      type="string",
 *      description="mlive: 是否有动画，1-是、0-否 intelligence: 是否有情报，1-是、0-否 lineup: 是否有阵容，1-是、0-否",
 *   ),
 *   @OA\Property(
 *      property="venue_id ",
 *      type="integer",
 *      description="场馆ID，没有不存在",
 *   ),
 *   @OA\Property(
 *      property="referee_id",
 *      type="integer",
 *      description="裁判id，没有不存在",
 *   ),
 *   @OA\Property(
 *      property="round",
 *      type="string",
 *      description="轮次，没有不存在  arr : stage_id：阶段id group_num: 第几组，1-A、2-B以此类推 round_num: 第几轮",
 *   ),
 *   @OA\Property(
 *      property="environment",
 *      type="string",
 *      description="weather:天气id<br/>1:局部有云<br/>2:多云<br/>3:局部有云/雨<br/>4:雪<br/>5:晴<br/>6:阴有雨/局部有雷暴<br/>7:阴<br/>8:薄雾<br/>9:阴有雨<br/>10:多云有雨<br/>11:多云有雨/局部有雷暴<br/>12:局部有云/雨和雷暴<br/>13:雾 pressure:气压 temperature:温度 wind:风速 humidity:湿度",
 *   ),
 *   @OA\Property(
 *      property="trend",
 *      type="string",
 *      description="比赛趋势",
 *   ),
 *   @OA\Property(
 *      property="live_url_1",
 *      type="string",
 *      description="直播地址",
 *   ),
 *   @OA\Property(
 *      property="live_url_2",
 *      type="string",
 *      description="直播地址",
 *   ),
 *   @OA\Property(
 *      property="live_url_3",
 *      type="string",
 *      description="直播地址",
 *   ),
 *   @OA\Property(
 *      property="pc_link",
 *      type="string",
 *      description="web版权直播地址",
 *   ),
 *   @OA\Property(
 *      property="mobile_link",
 *      type="string",
 *      description="wap版权直播地址",
 *   ),
 *   @OA\Property(
 *      property="state_str",
 *      type="string",
 *      description="比赛状态文本",
 *   ),
 *   @OA\Property(
 *      property="is_playing",
 *      type="integer",
 *      description="1未开赛，2比赛中，3已完赛",
 *   ),
 *   @OA\Property(
 *      property="home_team",
 *      type="object",
 *      description="主队字段信息",
 *      @OA\Property(
 *          property="competition_id",
 *          type="integer",
 *          description="赛事ID",
 *      ),
 *      @OA\Property(
 *          property="country_id",
 *          type="integer",
 *          description="国家ID",
 *      ),
 *      @OA\Property(
 *          property="name_zh",
 *          type="string",
 *          description="中文简体名称",
 *      ),
 *      @OA\Property(
 *          property="name_zht",
 *          type="string",
 *          description="粤语名称",
 *      ),
 *      @OA\Property(
 *          property="name_en",
 *          type="string",
 *          description="英文名称",
 *      ),
 *      @OA\Property(
 *          property="short_name_zh",
 *          type="string",
 *          description="中文简称",
 *      ),
 *      @OA\Property(
 *          property="short_name_zht",
 *          type="string",
 *          description="粤语简称",
 *      ),
 *      @OA\Property(
 *          property="short_name_en",
 *          type="string",
 *          description="英文简称",
 *      ),
 *      @OA\Property(
 *          property="logo",
 *          type="string",
 *          description="球队logo",
 *      ),
 *      @OA\Property(
 *          property="national",
 *          type="integer",
 *          description="是否国家队，1-是、0-否",
 *      ),
 *      @OA\Property(
 *          property="foundation_time",
 *          type="integer",
 *          description="成立时间",
 *      ),
 *      @OA\Property(
 *          property="website",
 *          type="string",
 *          description="球队官网",
 *      ),
 *      @OA\Property(
 *          property="manager_id",
 *          type="integer",
 *          description="教练id",
 *      ),
 *      @OA\Property(
 *          property="venue_id",
 *          type="integer",
 *          description="场馆ID",
 *      ),
 *      @OA\Property(
 *          property="market_value",
 *          type="string",
 *          description="市值",
 *      ),
 *      @OA\Property(
 *          property="market_value_currency",
 *          type="string",
 *          description="市值单位",
 *      ),
 *      @OA\Property(
 *          property="country_logo",
 *          type="string",
 *          description="国家队logo（为国家队时存在）",
 *      ),
 *      @OA\Property(
 *          property="total_players",
 *          type="integer",
 *          description="总球员数，-1表示没有该字段数据",
 *      ),
 *      @OA\Property(
 *          property="foreign_players",
 *          type="integer",
 *          description="非本土球员数，-1表示没有该字段数据",
 *      ),
 *      @OA\Property(
 *          property="national_players",
 *          type="integer",
 *          description="国家队球员数，-1表示没有该字段数据",
 *      ),
 *      @OA\Property(
 *          property="points",
 *          type="integer",
 *          description="积分",
 *      ),
 *      @OA\Property(
 *          property="ranking",
 *          type="integer",
 *          description="排名",
 *      ),
 *      @OA\Property(
 *          property="position_changed",
 *          type="integer",
 *          description="排名变化",
 *      ),
 *      @OA\Property(
 *          property="previous_points",
 *          type="integer",
 *          description="上次排名",
 *      ),
 *   ),
 *   @OA\Property(
 *      property="away_team",
 *      type="object",
 *      description="客队字段信息同主队",
 *   ),
 *
 * )
 **/


/**
 * @OA\Schema(
 *   schema="纳米-篮球比赛列表",
 *   @OA\Property(
 *      property="id",
 *      type="integer",
 *      description="比赛id",
 *   ),
 *   @OA\Property(
 *      property="season_id",
 *      type="integer",
 *      description="赛季ID",
 *   ),
 *   @OA\Property(
 *      property="competition_id",
 *      type="integer",
 *      description="赛事/联赛id",
 *   ),
 *   @OA\Property(
 *      property="league",
 *      type="object",
 *      description="赛事/联赛",
 *      @OA\Property(
 *          property="category_id",
 *          type="integer",
 *          description="分类ID",
 *      ),
 *      @OA\Property(
 *          property="country_id",
 *          type="integer",
 *          description="国家ID",
 *      ),
 *      @OA\Property(
 *          property="name_zh",
 *          type="string",
 *          description="中文名称",
 *      ),
 *      @OA\Property(
 *          property="name_zht",
 *          type="string",
 *          description="粤语名称",
 *      ),
 *      @OA\Property(
 *          property="name_en",
 *          type="string",
 *          description="英文名称",
 *      ),
 *      @OA\Property(
 *          property="short_name_zh",
 *          type="string",
 *          description="中文简称",
 *      ),
 *      @OA\Property(
 *          property="short_name_zht",
 *          type="string",
 *          description="粤语简称",
 *      ),
 *      @OA\Property(
 *          property="short_name_en",
 *          type="string",
 *          description="英文简称",
 *      ),
 *      @OA\Property(
 *          property="logo",
 *          type="string",
 *          description="logo",
 *      ),
 *   ),
 *   @OA\Property(
 *      property="match_time",
 *      type="integer",
 *      description="比赛开始时间(时间戳)",
 *   ),
 *   @OA\Property(
 *      property="status_id",
 *      type="integer",
 *      description="比赛状态：| 0 | 比赛异常，说明：暂未判断具体原因的异常比赛，可能但不限于：腰斩、取消等等，建议隐藏处理 | 1 | 未开赛 | 2 | 第一节 | 3 | 第一节完 | 4 | 第二节 | 5 | 第二节完 | 6 | 第三节 | 7 | 第三节完 | 8 | 第四节 | 9 | 加时 | 10 | 完场 | 11 | 中断 | 12 | 取消 | 13 | 延期 | 14 | 腰斩 | 15 | 待定",
 *   ),
 *   @OA\Property(
 *      property="home_team_id",
 *      type="integer",
 *      description="主队ID",
 *   ),
 *   @OA\Property(
 *      property="away_team_id",
 *      type="integer",
 *      description="客队ID",
 *   ),
 *   @OA\Property(
 *      property="neutral",
 *      type="integer",
 *      description="是否中立场，1-是、0-否",
 *   ),
 *   @OA\Property(
 *      property="note",
 *      type="string",
 *      description="备注",
 *   ),
 *   @OA\Property(
 *      property="home_scores",
 *      type="array",
 *      description=" 比分字段说明  Array[5] [0:第1节分数 - int 1:第2节分数 - int 2:第3节分数 - int 3:第4节分数 - int 4:加时分数 - int ]",
 *      @OA\Items(
 *                  type="integer",  example="0, 0, 0, 0, 0",
 *               )
 *   ),
 *   @OA\Property(
 *      property="away_scores",
 *      type="array",
 *      description=" 比分字段说明  Array[5] [0:第1节分数 - int 1:第2节分数 - int 2:第3节分数 - int 3:第4节分数 - int 4:加时分数 - int ]",
 *      @OA\Items(
 *                  type="integer",  example="0, 0, 0, 0, 0",
 *               )
 *   ),
 *   @OA\Property(
 *      property="home_position",
 *      type="string",
 *      description="主队排名",
 *   ),
 *   @OA\Property(
 *      property="away_position",
 *      type="string",
 *      description="客队排名",
 *   ),
 *   @OA\Property(
 *      property="coverage",
 *      type="string",
 *      description="mlive: 是否有动画，1-是、0-否 intelligence: 是否有情报，1-是、0-否 lineup: 是否有阵容，1-是、0-否",
 *   ),
 *   @OA\Property(
 *      property="venue_id ",
 *      type="integer",
 *      description="场馆ID，没有不存在",
 *   ),
 *   @OA\Property(
 *      property="round",
 *      type="integer",
 *      description="轮次，没有不存在 arr: stage_id：阶段id group_num: 第几组，1-A、2-B以此类推 round_num: 第几轮",
 *   ),
 *   @OA\Property(
 *      property="environment",
 *      type="string",
 *      description="weather:天气id<br/>1:局部有云<br/>2:多云<br/>3:局部有云/雨<br/>4:雪<br/>5:晴<br/>6:阴有雨/局部有雷暴<br/>7:阴<br/>8:薄雾<br/>9:阴有雨<br/>10:多云有雨<br/>11:多云有雨/局部有雷暴<br/>12:局部有云/雨和雷暴<br/>13:雾 pressure:气压 temperature:温度 wind:风速 humidity:湿度",
 *   ),
 *   @OA\Property(
 *      property="trend",
 *      type="string",
 *      description="比赛趋势",
 *   ),
 *   @OA\Property(
 *      property="period_count",
 *      type="integer",
 *      description="比赛总节数",
 *   ),
 *   @OA\Property(
 *      property="kind",
 *      type="integer",
 *      description="比赛类型id，1-常规赛、2-季后赛、3-季前赛、4-全明星、5-杯赛、0-无",
 *   ),
 *   @OA\Property(
 *      property="live_url_1",
 *      type="string",
 *      description="直播地址",
 *   ),
 *   @OA\Property(
 *      property="live_url_2",
 *      type="string",
 *      description="直播地址",
 *   ),
 *   @OA\Property(
 *      property="live_url_3",
 *      type="string",
 *      description="直播地址",
 *   ),
 *   @OA\Property(
 *      property="pc_link",
 *      type="string",
 *      description="web版权直播地址",
 *   ),
 *   @OA\Property(
 *      property="mobile_link",
 *      type="string",
 *      description="wap版权直播地址",
 *   ),
 *   @OA\Property(
 *      property="state_str",
 *      type="string",
 *      description="比赛状态文本",
 *   ),
 *   @OA\Property(
 *      property="is_playing",
 *      type="integer",
 *      description="1未开赛，2比赛中，3已完赛",
 *   ),
 *   @OA\Property(
 *      property="home_team",
 *      type="object",
 *      description="主队字段信息",
 *      @OA\Property(
 *          property="competition_id",
 *          type="integer",
 *          description="赛事ID",
 *      ),
 *      @OA\Property(
 *          property="conference_id",
 *          type="integer",
 *          description="赛区id，1-大西洋赛区、2-中部赛区、3-东南赛区、4-太平洋赛区、5-西北赛区、6-西南赛区、7-A组赛区、8-B组赛区、9-C组赛区、10-D组赛区（1~6:NBA 7~10:CBA）、0-无",
 *      ),
 *      @OA\Property(
 *          property="name_zh",
 *          type="string",
 *          description="中文简体名称",
 *      ),
 *      @OA\Property(
 *          property="name_zht",
 *          type="string",
 *          description="粤语名称",
 *      ),
 *      @OA\Property(
 *          property="name_en",
 *          type="string",
 *          description="英文名称",
 *      ),
 *      @OA\Property(
 *          property="short_name_zh",
 *          type="string",
 *          description="中文简称",
 *      ),
 *      @OA\Property(
 *          property="short_name_zht",
 *          type="string",
 *          description="粤语简称",
 *      ),
 *      @OA\Property(
 *          property="short_name_en",
 *          type="string",
 *          description="英文简称",
 *      ),
 *      @OA\Property(
 *          property="logo",
 *          type="string",
 *          description="国家logo",
 *      ),
 *   ),
 *   @OA\Property(
 *      property="away_team",
 *      type="object",
 *      description="客队字段信息同主队",
 *   ),
 *
 * )
 **/

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}
