<?php
/**
 * @OA\Schema(
 *   schema="dota2比赛列表",
 *   @OA\Items(ref="#/components/schemas/dota2比赛表"),
 * )
 **/

/**
 * @OA\Schema(
 *   schema="dota2比赛表",
 *      @OA\Property(
 *          property="tournament_id",
 *          type="integer",
 *          description="赛事id",
 *      ),
 *      @OA\Property(
 *          property="id",
 *          type="integer",
 *          description="比赛id",
 *      ),
 *      @OA\Property(
 *          property="match_time",
 *          type="integer",
 *          description="比赛开始时间",
 *      ),
 *      @OA\Property(
 *          property="status_id",
 *          type="integer",
 *          description="比赛状态，|0:比赛异常，说明：暂未判断具体原因的异常比赛，建议隐藏处理|1:未开赛|2:进行中|3:完场|11:中断|12:取消|13:延期|14:腰斩|15:待定",
 *      ),
 *      @OA\Property(
 *          property="home_id",
 *          type="integer",
 *          description="主队id",
 *      ),
 *      @OA\Property(
 *          property="away_id",
 *          type="integer",
 *          description="客队id",
 *      ),
 *      @OA\Property(
 *          property="home_score",
 *          type="integer",
 *          description="主队获胜局数",
 *      ),
 *      @OA\Property(
 *          property="away_score",
 *          type="integer",
 *          description="客队获胜局数",
 *      ),
 *      @OA\Property(
 *          property="animations",
 *          type="array",
 *          description="动画直播地址列表",
 *          @OA\Items(
 *              @OA\Property(
 *                  property="url",
 *                  type="string",
 *                  description="动画直播地址列表",
 *              ),
 *          ),
 *      ),
 *      @OA\Property(
 *          property="live_url_1",
 *          type="string",
 *          description="视频直播地址1，使用的优先顺序1>2>3,依次从视频直播地址1、2、3取数据",
 *      ),
 *      @OA\Property(
 *          property="live_url_2",
 *          type="string",
 *          description="视频直播地址2，使用的优先顺序1>2>3,依次从视频直播地址1、2、3取数据",
 *      ),
 *      @OA\Property(
 *          property="live_url_3",
 *          type="string",
 *          description="视频直播地址3，使用的优先顺序1>2>3,依次从视频直播地址1、2、3取数据",
 *      ),
 *      @OA\Property(
 *          property="status_str",
 *          type="string",
 *          description="比赛状态文本描述",
 *      ),
 *      @OA\Property(
 *          property="match_date",
 *          type="string",
 *          description="比赛日期",
 *      ),
 *      @OA\Property(
 *          property="tournament",
 *          type="array",
 *          description="赛事",
 *          @OA\Items(
 *              @OA\Property(
 *                  property="logo",
 *                  type="string",
 *                  description="赛事logo，列表的赛事logo从此字段中取",
 *              ),
 *          ),
 *      ),
 *      @OA\Property(
 *          property="home_team",
 *          ref="#/components/schemas/dota2战队表"
 *      ),
 *      @OA\Property(
 *          property="away_team",
 *          ref="#/components/schemas/dota2战队表"
 *      ),
 *      @OA\Property(
 *          property="match_single",
 *          ref="#/components/schemas/dota2比赛单局表"
 *      ),
 *   ),
 **/

/**
 * @OA\Schema(
 *   schema="dota2赛事表",
 *      @OA\Property(
 *          property="id",
 *          type="integer",
 *          description="赛事id",
 *      ),
 *      @OA\Property(
 *          property="status_id",
 *          type="integer",
 *          description="比赛状态，|0:比赛异常，说明：暂未判断具体原因的异常比赛，建议隐藏处理|1:未开赛|2:进行中|3:完场|11:中断|12:取消|13:延期|14:腰斩|15:待定",
 *      ),
 *      @OA\Property(
 *          property="name_zh",
 *          type="string",
 *          description="中文名称",
 *      ),
 *      @OA\Property(
 *          property="name_en",
 *          type="string",
 *          description="英文名称",
 *      ),
 *      @OA\Property(
 *          property="abbr_zh",
 *          type="string",
 *          description="中文简称",
 *      ),
 *      @OA\Property(
 *          property="abbr_en",
 *          type="string",
 *          description="英文简称",
 *      ),
 *      @OA\Property(
 *          property="logo",
 *          type="string",
 *          description="图标",
 *      ),
 *      @OA\Property(
 *          property="cover",
 *          type="string",
 *          description="封面",
 *      ),
 *      @OA\Property(
 *          property="start_time",
 *          type="integer",
 *          description="开始时间",
 *      ),
 *      @OA\Property(
 *          property="end_time",
 *          type="integer",
 *          description="结束时间",
 *      ),
 *      @OA\Property(
 *          property="city_name",
 *          type="string",
 *          description="举办地 中文名称",
 *      ),
 *      @OA\Property(
 *          property="city_name_en",
 *          type="string",
 *          description="举办地 英文名称",
 *      ),
 *      @OA\Property(
 *          property="price_pool",
 *          type="string",
 *          description="奖金池",
 *      ),
 *      @OA\Property(
 *          property="type",
 *          type="integer",
 *          description="赛事类型，1.国际邀请赛、2.甲级联赛、3.乙级联赛、4.预选赛、5.其他赛事、0.未知",
 *      ),
 *   ),
 **/

/**
 * @OA\Schema(
 *   schema="dota2战队表",
 *      @OA\Property(
 *          property="id",
 *          type="integer",
 *          description="战队id",
 *      ),
 *      @OA\Property(
 *          property="name_zh",
 *          type="string",
 *          description="中文名称",
 *      ),
 *      @OA\Property(
 *          property="name_en",
 *          type="string",
 *          description="英文名称",
 *      ),
 *      @OA\Property(
 *          property="abbr_zh",
 *          type="string",
 *          description="中文简称",
 *      ),
 *      @OA\Property(
 *          property="abbr_en",
 *          type="string",
 *          description="英文简称",
 *      ),
 *      @OA\Property(
 *          property="logo",
 *          type="string",
 *          description="图标",
 *      ),
 *      @OA\Property(
 *          property="country_id",
 *          type="integer",
 *          description="国家id",
 *      ),
 *      @OA\Property(
 *          property="region_id",
 *          type="integer",
 *          description="赛区id",
 *      ),
 *      @OA\Property(
 *          property="create_time",
 *          type="integer",
 *          description="成立时间",
 *      ),
 *      @OA\Property(
 *          property="total_earnings",
 *          type="string",
 *          description="总奖金",
 *      ),
 *   ),
 **/

/**
 * @OA\Schema(
 *   schema="dota2比赛单局表",
 *      @OA\Property(
 *          property="id",
 *          type="integer",
 *          description="比赛单局id",
 *      ),
 *      @OA\Property(
 *          property="match_id",
 *          type="integer",
 *          description="比赛id",
 *      ),
 *      @OA\Property(
 *          property="status_id",
 *          type="integer",
 *          description="比赛状态，|0:比赛异常，说明：暂未判断具体原因的异常比赛，建议隐藏处理|1:未开赛|2:进行中|3:完场|11:中断|12:取消|13:延期|14:腰斩|15:待定",
 *      ),
 *      @OA\Property(
 *          property="match_time",
 *          type="integer",
 *          description="比赛时间",
 *      ),
 *      @OA\Property(
 *          property="box_num",
 *          type="integer",
 *          description="第几局",
 *      ),
 *      @OA\Property(
 *          property="radiant",
 *          type="string",
 *          description="【天辉】id:战队id，win:胜负，1-胜、0-负，score:比分，tower:塔的状态，详见长连接 -> tower字段说明，barracks:兵营的状态，详见长连接 -> barracks字段说明，ban:禁选英雄ids，example：[137, 114, 2]，pick:选择英雄ids，example：[137, 114, 2]",
 *      ),
 *      @OA\Property(
 *          property="dire",
 *          type="string",
 *          description="【夜魇】id:战队id，win:胜负，1-胜、0-负，score:比分，tower:塔的状态，详见长连接 -> tower字段说明，barracks:兵营的状态，详见长连接 -> barracks字段说明，ban:禁选英雄ids，example：[137, 114, 2]，pick:选择英雄ids，example：[137, 114, 2]",
 *      ),
 *      @OA\Property(
 *          property="length_time",
 *          type="integer",
 *          description="比赛时长",
 *      ),
 *      @OA\Property(
 *          property="first_blood",
 *          type="integer",
 *          description="一血的战队id",
 *      ),
 *      @OA\Property(
 *          property="first_tower",
 *          type="integer",
 *          description="一塔的战队id",
 *      ),
 *      @OA\Property(
 *          property="first_roushan",
 *          type="integer",
 *          description="首肉山的战队id",
 *      ),
 *      @OA\Property(
 *          property="five_kill",
 *          type="integer",
 *          description="先五杀的战队id",
 *      ),
 *      @OA\Property(
 *          property="eco_list",
 *          type="string",
 *          description="经济曲线：天辉与夜魇的差值，按分钟数变化",
 *      ),
 *      @OA\Property(
 *          property="exp_list",
 *          type="string",
 *          description="经验曲线：天辉与夜魇的差值，按分钟数变化",
 *      ),
 *      @OA\Property(
 *          property="roshan_timer",
 *          type="integer",
 *          description="肉山刷新剩余时间-秒",
 *      ),
 *      @OA\Property(
 *          property="timer",
 *          type="string",
 *          description="比赛时间字段说明",
 *      ),
 *      @OA\Property(
 *          property="is_bp",
 *          type="integer",
 *          description="是否处于bp环节，1.是、0.否\r\n(注：bp环节不属于比赛时间)",
 *      ),
 *      @OA\Property(
 *          property="bp_data",
 *          type="string",
 *          description="bp数据",
 *      ),
 *
 *   ),
 **/
