<?php
/**
 * @OA\Schema(
 *   schema="用户表",
 *   @OA\Property(
 *      property="id",
 *      type="integer",
 *      description="id",
 *   ),
 *   @OA\Property(
 *      property="user_nicename",
 *      type="string",
 *      description="昵称",
 *   ),
 *   @OA\Property(
 *      property="avatar",
 *      type="string",
 *      description="头像",
 *   ),
 *   @OA\Property(
 *      property="avatar_thumb",
 *      type="string",
 *      description="头像缩略图",
 *   ),
 *   @OA\Property(
 *      property="sex",
 *      type="string",
 *      description="性别",
 *   ),
 *   @OA\Property(
 *      property="signature",
 *      type="string",
 *      description="签名",
 *   ),
 *   @OA\Property(
 *      property="coin",
 *      type="string",
 *      description="用户余额",
 *   ),
 *   @OA\Property(
 *      property="login_type",
 *      type="string",
 *      description="注册类型",
 *   ),
 *   @OA\Property(
 *      property="level",
 *      type="string",
 *      description="等级",
 *   ),
 *   @OA\Property(
 *      property="province",
 *      type="string",
 *      description="省份",
 *   ),
 *   @OA\Property(
 *      property="city",
 *      type="string",
 *      description="城市",
 *   ),
 *   @OA\Property(
 *      property="birthday",
 *      type="string",
 *      description="生日",
 *   ),
 *   @OA\Property(
 *      property="token",
 *      type="string",
 *      description="授权令牌",
 *   ),
 * )
 **/
